mkdir build
cd build

REM Configure step
cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" ^
 -DCMAKE_BUILD_TYPE=Release ^
 -DOCE_USE_TCL_TEST_FRAMEWORK:BOOL=OFF ^
 -DOCE_VISUALISATION:BOOL=ON ^
 -DOCE_OCAF:BOOL=ON ^
 -DOCE_DRAW:BOOL=ON ^
 -DOCE_DATAEXCHANGE:BOOL=ON ^
 -DOCE_NO_LIBRARY_VERSION=ON ^
 -DOCE_TESTING=OFF ^
 -DOCE_USE_PCH=OFF ^
 -DCMAKE_PREFIX_PATH="%LIBRARY_PREFIX%" ^
 -DCMAKE_SYSTEM_PREFIX_PATH="%LIBRARY_PREFIX%" ^
 -DOCE_INSTALL_LIB_DIR=lib ^
 -DOCE_INSTALL_BIN_DIR=bin ^
 -DOCE_WITH_FREEIMAGE=ON ^
 -DOCE_WITH_GL2PS=ON ^
 -DOCE_MULTITHREAD_LIBRARY=TBB ^
 -DGL2PS_INCLUDE_DIR="%LIBRARY_PREFIX%"\include\gl2ps ^
 -DFREEIMAGE_INCLUDE_DIR="%LIBRARY_PREFIX%"\include\FreeImage ^
 -DOCE_INSTALL_PREFIX="%LIBRARY_PREFIX%" -DOCE_ENABLE_DEB_FLAG=OFF ..
if errorlevel 1 exit 1
 
REM Build step 
ninja
if errorlevel 1 exit 1

REM Install step
ninja install
if errorlevel 1 exit 1

